name: Deploy PHP Code

on:
  push:
    branches:
      - main # Deploy only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_REMOTE_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy code via rsync
        env:
          SSH_REMOTE_SERVER_USERNAME: ${{ secrets.SSH_REMOTE_SERVER_USERNAME }}
          SSH_REMOTE_SERVER_IP: ${{ secrets.SSH_REMOTE_SERVER_IP }}
        run: |
          echo "Starting rsync..."
          rsync -avz --progress ./ ${{secrets.SSH_REMOTE_SERVER_USERNAME}}@${{secrets.SSH_REMOTE_SERVER_IP}}:/var/www/html/
          echo "rsync completed."
